### ISSUE TITLE
File "/home/kali/Tools/email-cracker/EmailCracker.py", line 81, in <module>

### ISSUE THREAD

**Issue by Youngplaskon** [Hack-BitGod/email-cracker#3]
┌──(root㉿Windows10-Pro)-[/home/kali/Tools/email-cracker]
└─# python3 EmailCracker.py

  _____ __  __    _    ___ _        ____ ____      _    ____ _  _______ ____  
 | ____|  \/  |  / \  |_ _| |      / ___|  _ \    / \  / ___| |/ / ____|  _ \ 
 |  _| | |\/| | / _ \  | || |     | |   | |_) |  / _ \| |   | ' /|  _| | |_) |
 | |___| |  | |/ ___ \ | || |___  | |___|  _ <  / ___ \ |___| . \| |___|  _ < 
 |_____|_|  |_/_/   \_\___|_____|  \____|_| \_\/_/   \_\____|_|\_\_____|_| \_\ 
                                                                         v1.0
Coded By : Hack-BitGod  

BitGod@Hack-BitGod:
2024-09-17 07:15:39,486 - INFO - SMTP connection established successfully.
2024-09-17 07:15:39,491 - ERROR - An unexpected error occurred: name 'os' is not defined
HackBitGod Email Cracker
TRYING WITH PASSWORDS IN: psw.list
Traceback (most recent call last):
  File "/home/kali/Tools/email-cracker/EmailCracker.py", line 81, in <module>
    user = raw_input("Enter The Victim's Email Address: ")
           ^^^^^^^^^
NameError: name 'raw_input' is not defined
                                                                                                                           
┌──(root㉿Windows10-Pro)-[/home/kali/Tools/email-cracker]
└─# ls
BitGod.png  EmailCracker.py  emailhack.php  httpd_install.sh  psw.list.txt  README.md

**Comment by pierceparks** [comment]
HACKERSPYTECH @ GMAIL . COM , helped me hack into my husband phone under 1 hours with out having physical assess to his phone hacked into my wife text messages, deleted text messages, call logs, viber messages, whats-app messages,Facebook messages and many more this hacker is true and reliable his services are cheap and affordable you all can also contact him for help tell him i refereed you am sure he will help you.

![Image](https://github.com/user-attachments/assets/69333667-936a-49f3-a2d9-03fffeb8df7f)

**Comment by HP-W11** [comment]
I had this too simplest way to fix it is to go into the file find line 81 and delete the "raw_" part from the input. It is because in new versions of python they renamed raw_input to just input so yeah.
